services:
  - type: web
    name: django-htmx-todo
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && gunicorn myproject.wsgi:application --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-service.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-service.onrender.com"
    autoDeploy: true
